[package]
name = "gpt_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
spinners = "4.1.0"
tokio = { version = "1.29.1", features = ["full"] }
